### ISSUE TITLE
Add FileHelper

### ISSUE THREAD

**Issue by c-butcher** [zibings/stoic-php-io#12]

**Comment by AndyM84** [comment]
@c-butcher, do you know if we can share namespaces between different repositories in composer?  For instance, it would seem to make more sense organization-wise to have things like the Sanitizer/ParameterHelper/etc live within the `Stoic\Utilities` namespace since they're just additional utilities.  Just not sure if that's supported by the autoloader?

**Comment by c-butcher** [comment]
Yep, you can have multiple packages use the same namespace. The only thing to be careful of is naming conflicts in your classes. So long as each package has unique class names, you should be good.

**Comment by AndyM84** [comment]
This looks like it's finished, so gonna close it and if we have issues we can open new issues.
